<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE albumesMortadelo [
    <!ELEMENT albumesMortadelo (album*)>
    <!ELEMENT album (nombre)>
    <!ATTLIST album fecha (1969|1970|1971|1972|1973|1974) #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
]>

<albumesMortadelo>
    <album fecha="1969">
        <nombre>"El sulfato atómico</nombre>
    </album>
    <album fecha="1970">
        <nombre>"La caja de diez cerrojos"</nombre>
    </album>
    <album fecha="1971">
        <nombre>"El otro yo del profesor Bacterio"</nombre>
    </album>
    <album fecha="1972">
        <nombre> "Los cacharros majaretas"</nombre>
    </album>
    <album fecha="1973">
        <nombre>"Las vacaciones de Mortadelo"</nombre>
    </album>
    <album fecha="1974">
        <nombre>"Descubre los secretos de Mortadelo"</nombre>
    </album>
</albumesMortadelo>

<!--Al poder modificar tatnto el dtd como el código en si una de las opciones podría ser añadir un atributo como elemento a album y 
    mantener un atributo como fecha pero separado como una secuencia -->